export * from './client';
export * from './api.iam';
export * from './api.admissions';
export * from './api.academics';
export * from './api.finance';
export * from './api.hr';
export * from './api.iqac';
export * from './api.operations';
export * from './api.settings';
