"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, Box, History, Radio, ShieldAlert } from "lucide-react";
import { useAuthedApi } from "@/lib/api";
import {
  createInventoryApi,
  type InventoryDetail,
} from "@/lib/api/api.inventory";
import { toast } from "@/lib/notifications/falcon-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export function InventoryDetailWorkspace({ recordId }: { recordId: string }) {
  const authed = useAuthedApi();
  const api = useMemo(() => createInventoryApi(authed), [authed]);
  const [detail, setDetail] = useState<InventoryDetail | null>(null);
  const [busy, setBusy] = useState(false);
  const [serial, setSerial] = useState("");
  const [tag, setTag] = useState("");
  const [reason, setReason] = useState("");
  const [quantity, setQuantity] = useState("1");
  const reload = useCallback(
    () =>
      api
        .get(recordId)
        .then(setDetail)
        .catch((error) => toast.error(error.message)),
    [api, recordId],
  );
  useEffect(() => void reload(), [reload]);
  async function mutate(work: () => Promise<unknown>) {
    setBusy(true);
    try {
      await work();
      toast.success("Inventory record updated");
      await reload();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Operation failed");
    } finally {
      setBusy(false);
    }
  }
  if (!detail)
    return (
      <div className="p-6 text-sm text-muted-foreground">
        Loading inventory record…
      </div>
    );
  const revision = Number(detail.aggregate_revision);
  const bindings =
    (detail.rfid?.bindings as Record<string, unknown>[] | undefined) ?? [];
  const pendingBinding = bindings.find(
    (binding) => binding.status === "ENCODED",
  );
  return (
    <div className="space-y-5 p-6">
      <div>
        <div className="flex flex-wrap items-center gap-2">
          <h1 className="text-2xl font-black">{detail.product_name}</h1>
          <Badge
            variant={
              detail.record_status === "ACTIVE"
                ? "success"
                : detail.record_status === "QUARANTINED"
                  ? "destructive"
                  : "outline"
            }
          >
            {detail.record_status}
          </Badge>
          <Badge variant="outline">{detail.record_type}</Badge>
        </div>
        <p className="mt-1 text-sm text-muted-foreground">
          {detail.university_asset_id ?? detail.lot_id} ·{" "}
          {detail.product_model_code} · {detail.batch_code}
        </p>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BadgeCheck className="h-5 w-5" />
              Identity preparation
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <Input
              placeholder="Manufacturer serial (manufacturer-issued only)"
              value={serial}
              onChange={(e) => setSerial(e.target.value)}
            />
            <Input
              placeholder="Initial location"
              value={detail.location_text ?? ""}
              readOnly
            />
            <Button
              disabled={busy || detail.record_status === "ACTIVE"}
              onClick={() =>
                void mutate(() =>
                  api.prepare(recordId, revision, {
                    manufacturer_serial: serial || undefined,
                    location_text:
                      detail.location_text || "Inventory receiving",
                  }),
                )
              }
            >
              Prepare university identity
            </Button>
            <p className="text-xs text-muted-foreground">
              Asset/Lot IDs are generated transactionally. Manufacturer serials
              are never generated by Falcon.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Radio className="h-5 w-5" />
              RFID binding
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <Input
              placeholder="Physical RFID tag UID"
              value={tag}
              onChange={(e) => setTag(e.target.value)}
            />
            <Button
              disabled={busy || !tag}
              onClick={() =>
                void mutate(() =>
                  api.encode(recordId, revision, {
                    physical_tag_uid: tag,
                    tag_technology: "SIMULATED_UHF",
                    encoder_device_id: "WEB-SIMULATOR",
                    encoded_payload_hash: "0".repeat(64),
                    key_version: "sim-v1",
                  }),
                )
              }
            >
              Encode / simulate tag
            </Button>
            {pendingBinding && (
              <Button
                variant="outline"
                disabled={busy}
                onClick={() =>
                  void mutate(() =>
                    api.verify(
                      recordId,
                      String(pendingBinding.rfid_binding_id),
                      revision,
                    ),
                  )
                }
              >
                Independently verify encoded tag
              </Button>
            )}
            <p className="text-xs text-muted-foreground">
              The logical RFID remains permanent; damaged physical tags are
              replaceable bindings.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Box className="h-5 w-5" />
              Activation and stock
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <Button
              disabled={busy || detail.record_status === "ACTIVE"}
              onClick={() =>
                void mutate(() => api.activate(recordId, revision))
              }
            >
              Sign and activate inventory identity
            </Button>
            {detail.record_type === "LOT" && (
              <>
                <Input
                  type="number"
                  min="0.001"
                  step="0.001"
                  value={quantity}
                  onChange={(e) => setQuantity(e.target.value)}
                />
                <Textarea
                  placeholder="Immutable movement reason"
                  value={reason}
                  onChange={(e) => setReason(e.target.value)}
                />
                <Button
                  variant="outline"
                  disabled={busy || !reason}
                  onClick={() =>
                    void mutate(() =>
                      api.moveLot(recordId, revision, {
                        movement_type: "CONSUMPTION",
                        quantity: Number(quantity),
                        reason,
                      }),
                    )
                  }
                >
                  Post lot consumption
                </Button>
              </>
            )}
            <p className="text-xs text-muted-foreground">
              {detail.lot_movements.length} immutable lot movement(s);{" "}
              {detail.identity_revisions.length} signed identity revision(s).
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ShieldAlert className="h-5 w-5" />
              Inventory discrepancy
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <Textarea
              placeholder="Describe inaccurate location, custodian, serial, tag or product data"
              value={reason}
              onChange={(e) => setReason(e.target.value)}
            />
            <Button
              variant="outline"
              disabled={busy || !reason}
              onClick={() =>
                void mutate(() =>
                  api.discrepancy(recordId, revision, {
                    discrepancy_type: "REPORTED_INACCURACY",
                    description: reason,
                    severity: "REVIEWABLE",
                  }),
                )
              }
            >
              Raise discrepancy ticket
            </Button>
            <p className="text-xs text-muted-foreground">
              {detail.discrepancies.length} discrepancy ticket(s). Protected
              data is never edited directly.
            </p>
          </CardContent>
        </Card>
      </div>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <History className="h-5 w-5" />
            Module 1–5 provenance
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm">
          {detail.audit_timeline.slice(0, 20).map((event) => (
            <div
              key={String(event.audit_event_id)}
              className="rounded border p-3"
            >
              <strong>{String(event.event_type).replaceAll("_", " ")}</strong>
              <span className="ml-2 text-muted-foreground">
                {new Date(String(event.created_at)).toLocaleString()}
              </span>
            </div>
          ))}
          {!detail.audit_timeline.length && (
            <p className="text-muted-foreground">No audit events available.</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
