ALTER TABLE campus_events
  ADD COLUMN IF NOT EXISTS funds_needed DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS hod_approval VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS hod_approved_by UUID REFERENCES users(user_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS hod_approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dean_approval VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS dean_approved_by UUID REFERENCES users(user_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS dean_approved_at TIMESTAMPTZ;
