export { DemoDataBanner } from './DemoDataBanner';
export { PresidentAlertsWidget } from './PresidentAlertsWidget';
export { AdmissionsDashboard } from './AdmissionsDashboard';
export { PlacementsDashboard } from './PlacementsDashboard';
export { AcademicsDashboard } from './AcademicsDashboard';
export { HrExecutiveDashboard } from './HrExecutiveDashboard';
export { HrAnalyticsDashboard } from './HrAnalyticsDashboard';
export { ExecutiveSummaryWithAlerts } from './ExecutiveSummaryWithAlerts';
export { ExecutiveInsightCard } from './ExecutiveInsightCard';
export { PresidentKpiCard } from './PresidentKpiCard';
export { FillStatusBadge, fillStatusFromPercent, LiveStatusBadge } from './FillStatusBadge';
export * from './mockData';
export * from './academicsMockData';
export * from './hrMockData';
export * from './insightsMockData';
export * from './smokeData';
export { ResultInsightsDashboard } from './ResultInsightsDashboard';
export * from './types';
